language: bash
dist: xenial
addons:
  apt:
    packages:
      - docker-ce
    update: true
services: docker
cache: false
git:
  depth: 1
#cache:
#  directories:
#    - /var/lib/apt/lists
env:
  - name=centos-7.4/dldt+ffmpeg
  - name=centos-7.4/dldt+gst
  - name=centos-7.4/ffmpeg
  - name=centos-7.4/gst
  - name=centos-7.4/nginx+rtmp
  - name=centos-7.4/ospray
  - name=centos-7.4/ospray+mpi+OpenImageIO
  - name=centos-7.5/dldt+ffmpeg
  - name=centos-7.5/dldt+gst
  - name=centos-7.5/ffmpeg
  - name=centos-7.5/gst
  - name=centos-7.5/nginx+rtmp
  - name=centos-7.5/ospray
  - name=centos-7.5/ospray+mpi+OpenImageIO
  - name=centos-7.6/dldt+ffmpeg
  - name=centos-7.6/dldt+gst
  - name=centos-7.6/ffmpeg
  - name=centos-7.6/gst
  - name=centos-7.6/nginx+rtmp
  - name=centos-7.6/ospray
  - name=centos-7.6/ospray+mpi+OpenImageIO
  - name=ubuntu-16.04/dldt+ffmpeg
  - name=ubuntu-16.04/dldt+gst
  - name=ubuntu-16.04/ffmpeg
  - name=ubuntu-16.04/gst
  - name=ubuntu-16.04/nginx+rtmp
  - name=ubuntu-16.04/ospray
  - name=ubuntu-16.04/ospray+mpi+OpenImageIO
  - name=ubuntu-18.04/dldt+ffmpeg
  - name=ubuntu-18.04/dldt+gst
  - name=ubuntu-18.04/ffmpeg
  - name=ubuntu-18.04/gst
  - name=ubuntu-18.04/nginx+rtmp
  - name=ubuntu-18.04/ospray
  - name=ubuntu-18.04/ospray+mpi+OpenImageIO

before_script:
  - docker version
script:
  - mkdir build && cd build
  - cmake ..
  - cd Xeon/${name} && make -j100
  - ctest
matrix:
  fast_finish: true
  allow_failures: # All images with GST will have GST SVT VP9 test failing. NGINX RTMP tests are not stable
    - name: centos-7.4/ffmpeg+gst+dev
    - env: name=centos-7.4/dldt+gst
    - env: name=centos-7.4/gst
    - env: name=centos-7.4/nginx+rtmp
    - name: centos-7.5/ffmpeg+gst+dev
    - env: name=centos-7.5/dldt+gst
    - env: name=centos-7.5/gst
    - env: name=centos-7.5/nginx+rtmp
    - name: centos-7.6/ffmpeg+gst+dev
    - env: name=centos-7.6/dldt+gst
    - env: name=centos-7.6/gst
    - env: name=centos-7.6/nginx+rtmp
    - name: ubuntu-16.04/ffmpeg+gst+dev
    - env: name=ubuntu-16.04/dldt+gst
    - env: name=ubuntu-16.04/gst
    - env: name=ubuntu-16.04/nginx+rtmp
    - name: ubuntu-18.04/ffmpeg+gst+dev
    - env: name=ubuntu-18.04/dldt+gst
    - env: name=ubuntu-18.04/gst
    - env: name=ubuntu-18.04/nginx+rtmp
  include:
    - name: centos-7.4/ffmpeg+gst+dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - travis_wait 150 ../script/travis_build.sh Xeon/centos-7.4/ffmpeg+gst+dev
        - cd Xeon/centos-7.4/ffmpeg+gst+dev
        - ctest
      after_failure:
        - tail --lines=5000 log_Xeon_centos74_ffmpeg_gst_dev.log
    - name: centos-7.5/ffmpeg+gst+dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - travis_wait 150 ../script/travis_build.sh Xeon/centos-7.5/ffmpeg+gst+dev
        - cd Xeon/centos-7.5/ffmpeg+gst+dev
        - ctest
      after_failure:
        - tail --lines=5000 log_Xeon_centos75_ffmpeg_gst_dev.log
    - name: centos-7.6/ffmpeg+gst+dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - travis_wait 150 ../script/travis_build.sh Xeon/centos-7.6/ffmpeg+gst+dev
        - cd Xeon/centos-7.6/ffmpeg+gst+dev
        - ctest
      after_failure:
        - tail --lines=5000 log_Xeon_centos76_ffmpeg_gst_dev.log
    - name: ubuntu-16.04/ffmpeg+gst+dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - travis_wait 150 ../script/travis_build.sh Xeon/ubuntu-16.04/ffmpeg+gst+dev
        - cd Xeon/ubuntu-16.04/ffmpeg+gst+dev
        - ctest
      after_failure:
        - tail --lines=5000 log_Xeon_ubuntu1604_ffmpeg_gst_dev.log
    - name: ubuntu-18.04/ffmpeg+gst+dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - travis_wait 150 ../script/travis_build.sh Xeon/ubuntu-18.04/ffmpeg+gst+dev
        - cd Xeon/ubuntu-18.04/ffmpeg+gst+dev
        - ctest
      after_failure:
        - tail --lines=5000 log_Xeon_ubuntu1804_ffmpeg_gst_dev.log